routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect','localizationRedirect','localeViewPath', 'httpsProtocol']
],
function()
{
    # User Login
    Route::group(['namespace' => 'Auth'], function() {
        Route::get('/login', 'LoginController@showUserLoginForm')->name('login');
        Route::post('/login', 'LoginController@userLogin')->name('user.submit.login');
        Route::post('/logout', 'LoginController@userLogout')->name('user.logout');
    });

    # Admin Login
    Route::group(['prefix' => 'admin-panel', 'namespace' => 'Auth\Admin'], function() {
        Route::get('/login', 'AdminLoginController@showAdminLoginForm')->name('admin-panel.login');
        Route::post('/login', 'AdminLoginController@adminLogin')->name('admin.submit.login');
        Route::post('/logout', 'AdminLoginController@adminLogout')->name('admin.logout');
    });

    // Password Reset Routes...
    Route::group(['prefix' => 'password'], function() {
        Route::get('/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.update');
        Route::post('/reset', 'Auth\ResetPasswordController@reset')->name('password.reset');
        Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
        Route::get('/email','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');
    });

    # Admin routes
    Route::group([
        'prefix'     => 'admin-panel',
        'namespace'  => 'Back',
        'middleware' => ['auth:admin', 'CheckAdminRole']
    ],
    function()
    {
        Route::get('/', 'DashboardController@index')->name('admin-panel');

        // admin -> roles Routes
        Route::resource('roles','RoleController', ['except' => ['show']]);
        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function() {
            Route::post('/ajax-delete-role',      'RoleController@DeleteRole')->name('ajax-delete-role');
            Route::post('/ajax-change-role-status', 'RoleController@ChangeStatus')->name('ajax-change-role-status');
            Route::get('/export',                 'RoleController@export')->name('export');
        });

        // admin -> users Routes
        Route::resource('employees', 'EmployeeController', ['except' => ['show']]);
        Route::group(['prefix' => 'employees', 'as' => 'employees.'], function() {
            Route::post('/ajax-delete-employee','EmployeeController@DeleteEmployee')->name('ajax-delete-employee');
            Route::post('/ajax-change-employee-status','EmployeeController@ChangeStatus')->name('ajax-change-employee-status');
            Route::get('/show/{id}','EmployeeController@showEmployee')->name('show-employee');
            Route::get('/export','EmployeeController@export')->name('export');
        });

        // admin -> Settings Routes
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function() {
            Route::post('/ajax-change-setting-status', 'SettingController@ChangeStatus')->name('ajax-change-setting-status');
            Route::get('/export',                    'SettingController@export')->name('export');
            Route::post('/update-all', 'SettingController@UpdateAll')->name('update-all');
            Route::post('/ajax-delete-setting', 'SettingController@DeleteSetting')->name('ajax-delete-setting');
            //Route::get('/show-push-notification', 'AdminController@ShowPushNotification')->name('show-push-notification');
            //Route::post('/show-push-notification-post', 'AdminController@ShowPushNotificationPost')->name('push-notification-post');
        });
        Route::resource('settings', 'SettingController');

        // admin -> Admins Routes
        Route::group(['prefix' => 'admins', 'as' => 'admins.'], function() {
            Route::get('/admin/profile',   'AdminController@adminProfile')->name('profile');
            Route::post('/admin/profile',  'AdminController@AdminUpdateProfile')->name('admin-profile-update');
            Route::post('/ajax-delete-admin',      'AdminController@DeleteAdmin')->name('ajax-delete-admin');
            Route::post('/ajax-change-admin-status', 'AdminController@ChangeStatus')->name('ajax-change-admin-status');
            Route::get('/show/{id}',               'AdminController@showAdmin')->name('show-admin');
            Route::get('/export',                  'AdminController@export')->name('export');
        });
        Route::resource('admins',      'AdminController', ['except' => ['show']]);

        Route::group(['prefix' => 'contacts', 'as' => 'contacts.'], function(){
            Route::get('/',        'AdminController@Contacts')->name('index');
            Route::post('/ajax-delete-contact', 'AdminController@DeleteContact')->name('ajax-delete-contact');
            Route::get('/{id}/message-details', 'AdminController@showMessageDetails')->name('message.details');
            Route::get('/{id}/send-message', 'AdminController@sendUserMessage')->name('send-user-message');
            Route::post('/users-send-email', 'AdminController@SendUserReplayMessage')->name('users-send-email');
            Route::get('/export', 'AdminController@ContactsExport')->name('export');
        });
    });

    # User Routes
    Route::group(['namespace' => 'Front'], function() {
        Route::get('/', 'HomeController@welcome');
        Route::get('/home', 'HomeController@index');
    });
});

app/Models/Employee.php
<?php

namespace App\Models;

use Exception;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class Employee extends Model
{
    protected $guarded = ['id'];

    protected $casts = ['status' => 'boolean'];

    public function setStatusAttribute($value)
    {
        if (is_null($value)) $value = false;

        $this->attributes['status'] = (boolean) $value;
    }

    public static function createEmployee(Request $request)
    {
        return Employee::create($request->except(['_token']));
    }

    public static function updateEmployee(Request $request, $currentEmployee)
    {
        return $currentEmployee->update($request->except(['_token']));
    }
}

app/Http/Controllers/Back/AdminController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Admin;
use App\Models\Contact;
use App\Models\Market;
use App\Models\Role;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\AdminsExport;
use App\Exports\ContactsExport;
use App\Exports\PaymentsExport;
use App\Exports\CommissionExport;
use App\Exports\MarketsCallsExport;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;

class AdminController extends Controller
{
    public function index()
    {
        return view('Back.Admins.index', ['admins' => Admin::where('role_id', '!=', 1)->get()]);
    }

    public function Contacts()
    {
        return view('Back.Admins.contacts',['contacts' => Contact::all()]);
    }

    public function showMessageDetails($id)
    {
        if (!$message = Contact::find($id)) return response()->json(['requestStatus'=>false,'message'=>trans('responseMessages.product-not-exist')]);

        return view('Back.Admins.messageDetailsModal', compact('message'))->render();
    }

    public function sendUserMessage($id)
    {
        if(!$message = Contact::find($id)) return response()->json(['requestStatus' => false,'message' => trans('back.message-not-exists')]);

        return view('Back.Admins.sendUserMessageModal', compact('message'));
    }

    public function SendUserReplayMessage(Request $request)
    {
        return Contact::sendUserReplayMessage($request);
    }

    public function export(Request $request){ return Excel::download(new AdminsExport, 'admins.xlsx'); }

    public function ContactsExport(Request $request) { return Excel::download(new ContactsExport, 'contacts.xlsx'); }

    public function showAdmin($admin_id)
    {
        return view('Back.Admins.show', ['admin' => Admin::findOrFail($admin_id)]);
    }

    public function ChangeStatus(Request $request)
    {
        if (!$updateStatus = Admin::updateStatus($request->all(), Admin::find($request->id)))
            return response()->json(['requestStatus' => false, 'message' => trans('api.server-internal-error')]);

        return response()->json(['requestStatus' => true, 'message' => translated('edit','admin')]);
    }

    public function AdminUpdateProfile(Requests\Back\EditAdminProfileRequest $request)
    {
        if (Admin::updateAdmin($request->except(['_token', 'submit']), Admin::find($request->admin_id)))
        {
            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else{request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if (request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            else{request()->session()->flash('status','danger');request()->session()->flash('message',__('Server Internal Error 500'));}
        }

        return redirect()->route('admins.profile');
    }

    public function adminProfile()
    {
        return view('Back.Admins.profile', ['admin' => Auth::user()]);
    }

    public function create()
    {
        return view('Back.Admins.create',['roles' => Role::getInSelectForm()]);
    }

    public function store(Requests\Back\CreateAdminRequest $request)
    {
        if(Admin::createAdmin($request->all()))
        {
            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else {request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if(request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Internal Server Error 500')]);
            else {request()->session()->flash('status','danger');request()->session()->flash('message',__('Internal Server Error 500'));}

            return back()->withInputs();
        }
        return redirect()->route('admins.index');
    }

    public function edit(Admin $admin)
    {
        return view('Back.Admins.edit', ['admin' => $admin, 'roles' => Role::getInSelectForm()]);
    }

    public function update(Requests\Back\EditAdminRequest $request, $id)
    {
        $currentAdmin = Admin::find($id);

        if (Admin::updateAdmin($request->all(), $currentAdmin)) {

            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else{request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if (request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            else{request()->session()->flash('status','danger');request()->session()->flash('message',__('Server Internal Error 500'));}
        }

        return redirect()->route('admins.edit', $currentAdmin->id);
    }

    public function DeleteAdmin(Request $request)
    {
        if(!$admin = Admin::findOrFail($request->id)) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, Admin is not exists !!']);

        try
        {
            $admin->delete();
            return response()->json(['deleteStatus' => true, 'message' => 'Admin Deleted Successfully']);
        }
        catch (Exception $e)
        {
            return response()->json(['deleteStatus' => false,'error' => 'Server Internal Error 500']);
        }
    }

    public function DeleteContact(Request $request)
    {
        if(!$contact = Contact::findOrFail($request->id)) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, Message is not exists !!']);

        try
        {
            $contact->delete();

            return response()->json(['deleteStatus' => true, 'message' => translated('delete','message')]);
        }
        catch (Exception $e)
        {
            return response()->json(['deleteStatus' => false,'error' => 'Server Internal Error 500']);
        }
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Employee;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('Back.index', ['usersChart' => Employee::orderBy('salary', 'DESC')->get()]);
    }
}

app/Http/Controllers/Back/EmployeeController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Employee;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\EmployeesExport;
use Illuminate\Support\Facades\File;
use Maatwebsite\Excel\Facades\Excel;

class EmployeeController extends Controller
{
    public function index()
    {
        return view('Back.Employees.index', ['employees' => Employee::all()]);
    }

    public function export(Request $request)
    {
        return Excel::download(new EmployeesExport, 'employees.xlsx');
    }

    public function ChangeStatus(Request $request)
    {
        if (!$updateStatus = updateStatus($request->all(), Employee::find($request->id)))
            return response()->json(['requestStatus' => false, 'message' => trans('api.server-internal-error')]);

        return response()->json(['requestStatus' => true, 'message' => translated('edit','employee')]);
    }

    public function showEmployee($employee_id)
    {
        return view('Back.Employees.show', ['employee' => Employee::findOrFail($employee_id)]);
    }

    public function create()
    {
        return view('Back.Employees.create', ['types' => ['design' => 'design', 'sales' => 'sales', 'development' => 'development']]);
    }

    public function store(Requests\Back\CreateEmployeeRequest $request)
    {
        if(Employee::createEmployee($request))
        {
            return response()->json(['requestStatus'=>true,'message'=>trans('back.add-done',['var'=>trans('back.t-employee')])]);
        }
        else
        {
            return response()->json(['requestStatus' => false, 'message' => __('Internal Server Error 500')]);
        }
    }

    public function edit(Employee $employee)
    {
        return view('Back.Employees.edit', ['employee' => $employee, 'types' => ['design' => 'design', 'sales' => 'sales', 'development' => 'development']]);
    }

    public function update(Requests\Back\EditEmployeeRequest $request, $id)
    {
        $currentEmployee = Employee::find($id);

        if (Employee::updateEmployee($request, $currentEmployee)) {

            if (request()->ajax())
                return response()->json(['requestStatus' => true, 'message' => trans('back.edit-done',['var'=>trans('back.t-employee')])]);
            else{
                request()->session()->flash('status','success');
                request()->session()->flash('message',trans('back.edit-done',['var'=>trans('back.t-employee')]));
            }
        }
        else
        {
            if (request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            else{
                 request()->session()->flash('status','danger');
                 request()->session()->flash('message',__('Server Internal Error 500'));
            }
        }

        return redirect()->route('employees.edit', $currentEmployee->id);
    }

    public function DeleteEmployee(Request $request)
    {
        $employee = Employee::find($request->id);

        if(!$employee) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, Employee is not exists !!']);

        try
        {
            File::delete('public/uploaded/employees' . $employee->image);

            $employee->delete();

            return response()->ajaxDeleteResponse('success', 'employee');
        }
        catch (Exception $e)
        {
            return response()->ajaxDeleteResponse('fails');
        }
    }
}

resources/views/Back/Employees/create.blade.php
@extends('Back.layouts.master')

@section('title', trans('back.create-var',['var'=>trans('back.employee')]))

@section('content')
    <!-- Page header -->
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4>
                    <i onClick="window.history.go(-1);" style="cursor: pointer;" class="icon-arrow-right6 position-left"></i>
                    <span class="text-semibold">@lang('back.home')</span> - @lang('back.create-var',['var'=>trans('back.employee')])
                </h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb" style="float: {{ floating('right','left') }};">
                <li><a href="{{ route('admin-panel') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a></li>
                <li><a href="{{ route('employees.index') }}"><i class="icon-users2 position-left"></i> @lang('back.employees')</a></li>
                <li class="active">@lang('back.create-var',['var'=>trans('back.employee')])</li>
            </ul>

            @include('Back.includes.quick-links')
        </div>
    </div>
    <!-- /page header -->
    <div class="panel panel-flat content">

        {!!
            Form::open([
                'route'  => 'employees.store',
                'method' => 'POST', 'class' => 'form-horizontal push-10-t employees ajax create', 'files' => true
            ])
        !!}

        <div class="panel-body">
            @include('Back.includes.flash')
            <div class="block block-rounded">
                <div class="block-header bg-smooth-dark col-md-10 col-md-offset-1">
                    @include('Back.Employees.form')
                </div>
            </div>
        </div>

        <div class="panel-footer"><input type="submit" name="submit" class="btn btn-primary" value="@lang('back.save')"></div>

        {!! Form::close() !!}
    </div>
@stop

resources/views/Back/Employees/edit.blade.php
@extends('Back.layouts.master')

@section('title', trans('back.edit-var',['var'=>trans('back.employee')]))

@section('content')
    <!-- Page header -->
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4>
                    <i onClick="window.history.go(-1);" style="cursor: pointer;" class="icon-arrow-right6 position-left"></i>
                    <span class="text-semibold">@lang('back.home')</span> - @lang('back.edit-var',['var'=>trans('back.employee')])
                </h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb" style="float: {{ floating('right','left') }};">
                <li><a href="{{ route('admin-panel') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a></li>
                <li><a href="{{ route('employees.index') }}"><i class="icon-users2 position-left"></i> @lang('back.employees')</a></li>
                <li class="active">@lang('back.edit-var',['var'=>trans('back.employee')])</li>
            </ul>

            @include('Back.includes.quick-links')
        </div>
    </div>
    <!-- /page header -->
    <div class="panel panel-flat content">

        {!!
            Form::model($employee,[
                'url'    => route('employees.update', $employee->id),
                'method' => 'PUT',
                'class'  => 'form-horizontal push-10-t employees ajax edit',
                'files'  => true,
            ])
        !!}

        <div class="panel-body">
            @include('Back.includes.flash')
            <div class="block block-rounded">
                <div class="block-header bg-smooth-dark col-md-10 col-md-offset-1">
                    @include('Back.Employees.form')
                </div>
            </div>
        </div>

        <div class="panel-footer"><input type="submit" name="submit" class="btn btn-primary" value="@lang('back.save')"></div>

        {!! Form::close() !!}
    </div>
@stop

resources/views/Back/Employees/form.blade.php
<div class="form-group">
	@include('Back.includes.inputs', [
		'errors' => $errors,
		'type'   => 'text',
		'name'   => 'name',
		'style'  => 'form-control form-data',
		'slug'   => trans('back.form-name'),
	])
</div>

<div class="form-group">
    @include('Back.includes.inputs', [
        'errors' => $errors,
        'type'   => 'text',
        'name'   => 'salary',
        'style'  => 'form-control form-data',
        'slug'   => trans('back.form-salary'),
    ])
</div>

<div class="form-group">
    @include('Back.includes.inputs', [
        'errors' => $errors,
        'type'   => 'select',
        'name'   => 'type',
        'list'   => count($types) > 0 ? ['' => trans('back.select-a-value')] + $types : [0 => trans('back.no-value')],
        'style'  => 'form-control form-data',
        'slug'   => trans('back.form-employee-type'),
    ])
</div>

<div class="form-group">
	<div class="checkbox checkbox-switchery switchery-lg">
		<label>
			@if(isset($employee)) @php $status = $employee->status == 1 ? true : false; @endphp

			@else @php $status = true; @endphp @endif

			{!! Form::checkbox('status',1, $status,['class'=>'form-control switchery form-data','id' => 'status']) !!}

			@lang('back.form-status')
		</label>
	</div>
</div>

resources/views/Back/Employees/index.blade.php
@extends('Back.layouts.master')

@section('title', trans('back.employees'))

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4>
                    <i onClick="window.history.go(-1);" style="cursor: pointer;" class="icon-arrow-right6 position-left"></i>
                    <span class="text-semibold">@lang('back.dashboard')</span> - @lang('back.employees')
                </h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb" style="float: {{ floating('right','left') }};">
                <li><a href="{{ route('admin-panel') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a></li>
                <li class="active">@lang('back.employees')</li>
            </ul>

            @include('Back.includes.quick-links')
        </div>
    </div>
    <!-- /page header -->

    <!-- Basic datatable -->
    <div class="panel panel-flat" dir="{{ direction() }}" style="margin: 20px;">
        <div class="panel-heading">
            @include('Back.includes.table-header', ['collection' => $employees, 'name' => 'employees', 'icon' => 'employees'])
        </div>

        <table class="table datatable-basic" id="employees" style="font-size: 16px;">
            <thead>
                <tr>
                    <th>#</th>
                    <th>@lang('back.form-name')</th>
                    <th>@lang('back.form-salary')</th>
                    <th>@lang('back.form-bonus')</th>
                    <th>@lang('back.form-employee-type')</th>
                    <th>@lang('back.since')</th>
                    <th>@lang('back.form-status')</th>
                    <th class="text-center">@lang('back.form-actions')</th>
                </tr>
            </thead>
            <tbody>
                @foreach($employees as $employee)
                <tr id="employee-row-{{ $employee->id }}">
                    <td>{{ $employee->id }}</td>

                    <td><a href="{{ route('employees.show-employee', $employee->id) }}"> {{ $employee->name ?? trans('back.no-value') }}</a></td>

                    <td>${{ $employee->salary }}</td>

                    <td>${{ $employee->bonus }}</td>

                    <td>{{ $employee->type }}</td>

                    <td>{{ $employee->created_at->diffForHumans() }}</td>

                    @include('Back.includes.chnageModelStatus', ['model' => $employee])

                    <td class="text-center">
                        @include('Back.includes.edit-delete', ['route' => 'employees', 'model' => $employee])
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic datatable -->
@stop

@section('scripts')

<script>
    function isChecked(value, id){
        if(value === 'checked'){
            $('#active-id-'+id).attr('onclick', 'isChecked("null", "'+id+'")');
        }else{
            $('#active-id-'+id).attr('onclick', 'isChecked("checked", "'+id+'")');
        }
        $.ajax({
            type: 'POST',
            url: '{{ route('employees.ajax-change-employee-status') }}',
            data: { id: id, value: value },
            success: function(response) {
                new PNotify({
                    title: 'Success notice',
                    text: response.message,
                    addclass: 'bg-success stack-top-right',
                    stack: {"dir1": "down", "dir2": "right", "push": "top"}
                });
            },
            error: (e) => console.error(e),
        });
    }

    $('a.delete-action').on('click', function(e)
    {
        var id = $(this).data('id');
        var tbody = $('table#employees tbody');
        var count = tbody.data('count');

        e.preventDefault();

        swal({
            title: "هل انت متأكد من حذف هذا الموظف",
            text: "سيتم الحذف بالانتقال لسلة المهملات",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                var tbody = $('table#employees tbody');
                var count = tbody.data('count');

                $.ajax({
                    type: 'POST',
                    url: '{{ route('employees.ajax-delete-employee') }}',
                    data: {id: id},
                    success: function(response)
                    {
                        if(response.deleteStatus)
                        {
                            $('#employee-row-'+id).fadeOut(); count = count - 1;tbody.attr('data-count', count);
                            swal(response.message, {icon: "success"});
                        }
                        else
                        {
                            swal(response.error);
                        }
                    },
                    error: function(x) { crud_handle_server_errors(x); },
                    complete: function() {
                        if(count === 1) tbody.append(`<tr><td colspan="5"><strong>No data available in table</strong></td></tr>`);
                    }
                });
            }
            else
            {
                swal({
                    title: "رسالة",
                    text: "تم إلغاء العملية",
                    icon: "success",
                    button: "حسنا",
                });
            }
        });
    });
</script>

@stop

resources/views/Back/Employees/show.blade.php
@extends('Back.layouts.master')

@section('title', $employee->name)

@section('content')
    <!-- Page header -->
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4>
                    <i onClick="window.history.go(-1);" style="cursor: pointer;" class="icon-arrow-right6 position-left"></i>
                    <span class="text-semibold">@lang('back.home')</span> - {{ ucwords($employee->name) }}
                </h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb" style="float: {{ floating('right','left') }};">
                <li><a href="{{ route('admin-panel') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a></li>
                <li><a href="{{ route('users.index') }}"><i class="icon-users position-left"></i> @lang('back.users')</a></li>
                <li class="active">{{ $employee->name }}</li>
            </ul>

            @include('Back.includes.quick-links')
        </div>
    </div>
    <!-- /page header -->
    <div class="content">
    	<div class="row">
    		<div class="col-md-8 col-md-offset-2">
                <!-- Basic table -->
                <div class="panel panel-flat">
                    <div class="panel-body">
                    	<div class="row">
                    		<div class="col-md-3" style="float: {{ floating('right', 'left') }}">
                    			<div class="thumbnail">
								<div class="thumb">
									<img style="width: 300px;height: 200px;" src="{{ url('public/admin/img/avatar10.jpg') }}" alt="">
									<div class="caption-overflow">
										<span>
											<a href="{{ route('employees.edit', $employee->id) }}" class="btn btn-info btn-sm">@lang('back.edit')</a>
										</span>
									</div>
								</div>

								<div class="caption">
									<h6 class="text-semibold no-margin-top" title="{{ $employee->name }}">
										{{ ucwords(str()->limit($employee->name, 30, '...')) }}
									</h6>
								</div>
							</div>
                    		</div>
                    		<div class="col-md-9" style="float: {{ floating('left', 'right') }}">
								<div class="well">
				                    <dl dir="{{ direction() }}">
										<dt>@lang('back.form-status')</dt>
										<dd>
						                    @if($employee->status == 1) <span class="label label-success">@lang('back.active')</span>
						                    @else <span class="label label-danger">@lang('back.disactive')</span>
						                    @endif
										</dd>

										<dt>@lang('back.since')</dt>
										<dd>{{ $employee->created_at->diffForHumans() }}</dd>
									</dl>
								</div>
                    		</div>
                    	</div>
                    </div>
                </div>
                <!-- /basic table -->
    		</div>
    	</div>
    </div>
@stop