routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect','localizationRedirect','localeViewPath', 'httpsProtocol']
],
function()
{
    # User Login
    Route::group(['namespace' => 'Auth'], function() {
        Route::get('/login', 'LoginController@showUserLoginForm')->name('login');
        Route::post('/login', 'LoginController@userLogin')->name('user.submit.login');
        Route::post('/logout', 'LoginController@userLogout')->name('user.logout');
    });

    # Admin Login
    Route::group(['prefix' => 'admin-panel', 'namespace' => 'Auth\Admin'], function() {
        Route::get('/login', 'AdminLoginController@showAdminLoginForm')->name('admin-panel.login');
        Route::post('/login', 'AdminLoginController@adminLogin')->name('admin.submit.login');
        Route::post('/logout', 'AdminLoginController@adminLogout')->name('admin.logout');
    });

    // Password Reset Routes...
    Route::group(['prefix' => 'password'], function() {
        Route::get('/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.update');
        Route::post('/reset', 'Auth\ResetPasswordController@reset')->name('password.reset');
        Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
        Route::get('/email','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');
    });

    # Admin routes
    Route::group([
        'prefix'     => 'admin-panel',
        'namespace'  => 'Back',
        'middleware' => ['auth:admin', 'CheckAdminRole']
    ],
    function()
    {
        Route::get('/', 'DashboardController@index')->name('admin-panel');

        // admin -> roles Routes
        Route::resource('roles','RoleController', ['except' => ['show']]);
        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function() {
            Route::post('/ajax-delete-role',      'RoleController@DeleteRole')->name('ajax-delete-role');
            Route::post('/ajax-change-role-status', 'RoleController@ChangeStatus')->name('ajax-change-role-status');
            Route::get('/export',                 'RoleController@export')->name('export');
        });

        // admin -> users Routes
        Route::resource('employees', 'EmployeeController', ['except' => ['show']]);
        Route::group(['prefix' => 'employees', 'as' => 'employees.'], function() {
            Route::post('/ajax-delete-employee','EmployeeController@DeleteEmployee')->name('ajax-delete-employee');
            Route::post('/ajax-change-employee-status','EmployeeController@ChangeStatus')->name('ajax-change-employee-status');
            Route::get('/show/{id}','EmployeeController@showEmployee')->name('show-employee');
            Route::get('/export','EmployeeController@export')->name('export');
        });

        // admin -> Settings Routes
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function() {
            Route::post('/ajax-change-setting-status', 'SettingController@ChangeStatus')->name('ajax-change-setting-status');
            Route::get('/export',                    'SettingController@export')->name('export');
            Route::post('/update-all', 'SettingController@UpdateAll')->name('update-all');
            Route::post('/ajax-delete-setting', 'SettingController@DeleteSetting')->name('ajax-delete-setting');
            //Route::get('/show-push-notification', 'AdminController@ShowPushNotification')->name('show-push-notification');
            //Route::post('/show-push-notification-post', 'AdminController@ShowPushNotificationPost')->name('push-notification-post');
        });
        Route::resource('settings', 'SettingController');

        // admin -> Admins Routes
        Route::group(['prefix' => 'admins', 'as' => 'admins.'], function() {
            Route::get('/admin/profile',   'AdminController@adminProfile')->name('profile');
            Route::post('/admin/profile',  'AdminController@AdminUpdateProfile')->name('admin-profile-update');
            Route::post('/ajax-delete-admin',      'AdminController@DeleteAdmin')->name('ajax-delete-admin');
            Route::post('/ajax-change-admin-status', 'AdminController@ChangeStatus')->name('ajax-change-admin-status');
            Route::get('/show/{id}',               'AdminController@showAdmin')->name('show-admin');
            Route::get('/export',                  'AdminController@export')->name('export');
        });
        Route::resource('admins',      'AdminController', ['except' => ['show']]);

        Route::group(['prefix' => 'contacts', 'as' => 'contacts.'], function(){
            Route::get('/',        'AdminController@Contacts')->name('index');
            Route::post('/ajax-delete-contact', 'AdminController@DeleteContact')->name('ajax-delete-contact');
            Route::get('/{id}/message-details', 'AdminController@showMessageDetails')->name('message.details');
            Route::get('/{id}/send-message', 'AdminController@sendUserMessage')->name('send-user-message');
            Route::post('/users-send-email', 'AdminController@SendUserReplayMessage')->name('users-send-email');
            Route::get('/export', 'AdminController@ContactsExport')->name('export');
        });
    });

    # User Routes
    Route::group(['namespace' => 'Front'], function() {
        Route::get('/', 'HomeController@welcome');
        Route::get('/home', 'HomeController@index');
    });
});

app/Http/Controllers/Back/AdminController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Admin;
use App\Models\Contact;
use App\Models\Market;
use App\Models\Role;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\AdminsExport;
use App\Exports\ContactsExport;
use App\Exports\PaymentsExport;
use App\Exports\CommissionExport;
use App\Exports\MarketsCallsExport;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;

class AdminController extends Controller
{
    public function index()
    {
        return view('Back.Admins.index', ['admins' => Admin::where('role_id', '!=', 1)->get()]);
    }

    public function Contacts()
    {
        return view('Back.Admins.contacts',['contacts' => Contact::all()]);
    }

    public function showMessageDetails($id)
    {
        if (!$message = Contact::find($id)) return response()->json(['requestStatus'=>false,'message'=>trans('responseMessages.product-not-exist')]);

        return view('Back.Admins.messageDetailsModal', compact('message'))->render();
    }

    public function sendUserMessage($id)
    {
        if(!$message = Contact::find($id)) return response()->json(['requestStatus' => false,'message' => trans('back.message-not-exists')]);

        return view('Back.Admins.sendUserMessageModal', compact('message'));
    }

    public function SendUserReplayMessage(Request $request)
    {
        return Contact::sendUserReplayMessage($request);
    }

    public function export(Request $request){ return Excel::download(new AdminsExport, 'admins.xlsx'); }

    public function ContactsExport(Request $request) { return Excel::download(new ContactsExport, 'contacts.xlsx'); }

    public function showAdmin($admin_id)
    {
        return view('Back.Admins.show', ['admin' => Admin::findOrFail($admin_id)]);
    }

    public function ChangeStatus(Request $request)
    {
        if (!$updateStatus = Admin::updateStatus($request->all(), Admin::find($request->id)))
            return response()->json(['requestStatus' => false, 'message' => trans('api.server-internal-error')]);

        return response()->json(['requestStatus' => true, 'message' => translated('edit','admin')]);
    }

    public function AdminUpdateProfile(Requests\Back\EditAdminProfileRequest $request)
    {
        if (Admin::updateAdmin($request->except(['_token', 'submit']), Admin::find($request->admin_id)))
        {
            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else{request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if (request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            else{request()->session()->flash('status','danger');request()->session()->flash('message',__('Server Internal Error 500'));}
        }

        return redirect()->route('admins.profile');
    }

    public function adminProfile()
    {
        return view('Back.Admins.profile', ['admin' => Auth::user()]);
    }

    public function create()
    {
        return view('Back.Admins.create',['roles' => Role::getInSelectForm()]);
    }

    public function store(Requests\Back\CreateAdminRequest $request)
    {
        if(Admin::createAdmin($request->all()))
        {
            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else {request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if(request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Internal Server Error 500')]);
            else {request()->session()->flash('status','danger');request()->session()->flash('message',__('Internal Server Error 500'));}

            return back()->withInputs();
        }
        return redirect()->route('admins.index');
    }

    public function edit(Admin $admin)
    {
        return view('Back.Admins.edit', ['admin' => $admin, 'roles' => Role::getInSelectForm()]);
    }

    public function update(Requests\Back\EditAdminRequest $request, $id)
    {
        $currentAdmin = Admin::find($id);

        if (Admin::updateAdmin($request->all(), $currentAdmin)) {

            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else{request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if (request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            else{request()->session()->flash('status','danger');request()->session()->flash('message',__('Server Internal Error 500'));}
        }

        return redirect()->route('admins.edit', $currentAdmin->id);
    }

    public function DeleteAdmin(Request $request)
    {
        if(!$admin = Admin::findOrFail($request->id)) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, Admin is not exists !!']);

        try
        {
            $admin->delete();
            return response()->json(['deleteStatus' => true, 'message' => 'Admin Deleted Successfully']);
        }
        catch (Exception $e)
        {
            return response()->json(['deleteStatus' => false,'error' => 'Server Internal Error 500']);
        }
    }

    public function DeleteContact(Request $request)
    {
        if(!$contact = Contact::findOrFail($request->id)) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, Message is not exists !!']);

        try
        {
            $contact->delete();

            return response()->json(['deleteStatus' => true, 'message' => translated('delete','message')]);
        }
        catch (Exception $e)
        {
            return response()->json(['deleteStatus' => false,'error' => 'Server Internal Error 500']);
        }
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Employee;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('Back.index', ['usersChart' => Employee::orderBy('salary', 'DESC')->get()]);
    }
}

app/Http/Controllers/Back/EmployeeController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Employee;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\EmployeesExport;
use Illuminate\Support\Facades\File;
use Maatwebsite\Excel\Facades\Excel;

class EmployeeController extends Controller
{
    public function index()
    {
        return view('Back.Employees.index', ['employees' => Employee::all()]);
    }

    public function export(Request $request)
    {
        return Excel::download(new EmployeesExport, 'employees.xlsx');
    }

    public function ChangeStatus(Request $request)
    {
        if (!$updateStatus = updateStatus($request->all(), Employee::find($request->id)))
            return response()->json(['requestStatus' => false, 'message' => trans('api.server-internal-error')]);

        return response()->json(['requestStatus' => true, 'message' => translated('edit','employee')]);
    }

    public function showEmployee($employee_id)
    {
        return view('Back.Employees.show', ['employee' => Employee::findOrFail($employee_id)]);
    }

    public function create()
    {
        return view('Back.Employees.create', ['types' => ['design' => 'design', 'sales' => 'sales', 'development' => 'development']]);
    }

    public function store(Requests\Back\CreateEmployeeRequest $request)
    {
        if(Employee::createEmployee($request))
        {
            return response()->json(['requestStatus'=>true,'message'=>trans('back.add-done',['var'=>trans('back.t-employee')])]);
        }
        else
        {
            return response()->json(['requestStatus' => false, 'message' => __('Internal Server Error 500')]);
        }
    }

    public function edit(Employee $employee)
    {
        return view('Back.Employees.edit', ['employee' => $employee, 'types' => ['design' => 'design', 'sales' => 'sales', 'development' => 'development']]);
    }

    public function update(Requests\Back\EditEmployeeRequest $request, $id)
    {
        $currentEmployee = Employee::find($id);

        if (Employee::updateEmployee($request, $currentEmployee)) {

            if (request()->ajax())
                return response()->json(['requestStatus' => true, 'message' => trans('back.edit-done',['var'=>trans('back.t-employee')])]);
            else{
                request()->session()->flash('status','success');
                request()->session()->flash('message',trans('back.edit-done',['var'=>trans('back.t-employee')]));
            }
        }
        else
        {
            if (request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            else{
                 request()->session()->flash('status','danger');
                 request()->session()->flash('message',__('Server Internal Error 500'));
            }
        }

        return redirect()->route('employees.edit', $currentEmployee->id);
    }

    public function DeleteEmployee(Request $request)
    {
        $employee = Employee::find($request->id);

        if(!$employee) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, Employee is not exists !!']);

        try
        {
            File::delete('public/uploaded/employees' . $employee->image);

            $employee->delete();

            return response()->ajaxDeleteResponse('success', 'employee');
        }
        catch (Exception $e)
        {
            return response()->ajaxDeleteResponse('fails');
        }
    }
}

resources/views/Back/includes/chnageModelStatus.blade.php
<td>
    <div class="checkbox checkbox-switchery switchery-lg">
        <label>
            @if($model->status == 1)
                <input
                    type="checkbox" onclick="isChecked('checked', '{{ $model->id }}');"
                    id="active-id-{{ $model->id }}" checked value="{{ $model->id }}"
                    name="status" class="form-control switchery form-data" id="status">
            @else
                <input
                    type="checkbox" onclick="isChecked('null', '{{ $model->id }}');"
                    id="active-id-{{ $model->id }}" value="{{ $model->id }}"
                    name="status" class="form-control switchery form-data" id="status">
            @endif
        </label>
    </div>
</td>

resources/views/Back/includes/edit-delete.blade.php
<ul class="icons-list">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>

        <ul class="dropdown-menu dropdown-menu-{{ floating('right', 'left') }}">
            <li><a href="{{ route($route.'.edit', $model->id) }}"><i class="icon-database-edit2"></i>@lang('back.edit')</a></li>
            <li>
                <a data-id="{{ $model->id }}" class="delete-action" href="{{ localeUrl('/admin-panel/'.$route.'/'.$model->id) }}">
                    <i class="icon-database-remove"></i>@lang('back.delete')
                </a>
            </li>
        </ul>
    </li>
</ul>

resources/views/Back/includes/flash.blade.php
<?php
	$messagesCount = 0;
	foreach (Session::all() as $key => $value) {
		if(strpos($key, 'message') !== false) $messagesCount ++;
	}
?>
@for($i = 0; $i <= $messagesCount ; $i ++)
	<?php $num = ($i == 0) ? '' : $i; ?>
	@if(Session::has('message'.$num))

		<div class="alert alert-{{ Session::get('status'.$num) }} alert-dismissible {{ Session::get('status'.$num) == 'success' ? 'alert-arrow-right' : '' }} ">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<h4><i class="icon fa fa-ban"></i> Alert!</h4>
			{{ Session::get('message'.$num) }}
        </div>

    @endif
@endfor

@if ($errors->first() || Session::has('custErrors'))

	<div class="alert alert-danger  alert-bordered flash-messages">
			<button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">{{ __('titles.close')}}</span></button>
			<p>{{ __('responseMessages.validation-error')}}.</p>
    </div>

@endif
<div id="ajax-messages"></div>

resources/views/Back/includes/inputs.blade.php
@if($type == 'password_confirmation')

	<div class="col-xs-{{ isset($col) ? $col : '12' }} @error($name) 'has-error' @enderror">
		<div class="form-valid floating">
			<label for="password_confirmation">{{ isset($slug) ? ucwords($slug) : '' }}</label>
			{!! Form::password('password_confirmation',['class'=>'form-control form-data','dir'=>direction(),'id'=>'password_confirmation']) !!}
		</div>
        @error($name) <span><strong>{{ $message }}</strong></span> @enderror
	</div>

@elseif($type == 'password')

	<div class="col-xs-{{ isset($col) ? $col : '12' }} @error($name) 'has-error' @enderror">
		<div class="form-valid floating">
			<label for="password">{{ isset($slug) ? ucwords($slug) : '' }}</label>
			{!! Form::password('password', ['class'=>'form-control form-data','dir'=>direction(),'id' => 'password']) !!}
		</div>
        @error($name) <span><strong>{{ $message }}</strong></span> @enderror
	</div>

@elseif($type == 'select')

	<div class="col-xs-{{ isset($col) ? $col : '12' }} @error($name) 'has-error' @enderror">
		<div class="form-valid floating">
			<label for="{{ $name }}">{{ isset($slug) ? ucwords($slug) : '' }}</label>
			{!! Form::select($name, $list, null, ['class'=>'form-control form-data','dir'=>direction(),'id' => $name]) !!}
		</div>
        @error($name) <span><strong>{{ $message }}</strong></span> @enderror
	</div>

@elseif($type == 'image')
	<div class="col-xs-{{ isset($col) ? $col : '12' }} @error($name) 'has-error' @enderror">
		<div class="row img-media">
			<div class="col-xs-12">
				<div class="form-valid">
					<label for="image">{{ isset($slug) ? ucwords($slug) : '' }}</label><br>
					<input type="file" class="file-styled {{ $style }}" id="image" accept="image/*" name="image">
					{{-- <input type="file" class="" id="image" accept="image/*" name="image"> --}}
                    @error($name) <span><strong>{{ $message }}</strong></span> @enderror
				</div>
			</div>
		</div>
	</div>

@elseif($type == 'text')

	<div class="col-xs-{{ isset($col) ? $col : '12' }}">
		<div class="form-valid floating @error($name) 'has-error' @enderror">
			<label for="{{ $name }}">{{ isset($slug) ? ucwords($slug) : '' }}</label>
			{!! Form::text($name, null, ['class'=>$style,'dir'=>direction(),'id' => $name, 'maxlength' => isset($attr) ? $attr : '']) !!}
			@error($name) <span><strong>{{ $message }}</strong></span> @enderror
		</div>
	</div>

@else

	<div class="col-xs-{{ isset($col) ? $col : '12' }} {{ $errors->first($name , 'has-error') }}">
		<div class="form-valid floating">
			<label for="{{ $name }}">{{ isset($slug) ? ucwords($slug) : '' }}</label>
			{!! Form::{$type}($name, null, ['class'=>$style,'dir'=>direction(),'id' => $name]) !!}
			{!! $errors->first($name , '<div class="help-block text-right animated fadeInDown val-error">:message</div>') !!}
		</div>
	</div>

@endif

resources/views/Back/includes/is-active.blade.php
@if($status == 1)
	<span class="label label-success" style="font-size: 15px;">@lang('back.active')</span>
@else
	<span class="label label-danger" style="font-size: 15px;">@lang('back.disactive')</span>
@endif

resources/views/Back/includes/logout.blade.php
<a href="{{ route($route) }}" onclick="event.preventDefault();document.getElementById('logout-form-'{{ $id }}).submit();">
    <i class="icon-switch2"></i> @lang('backend.logout')
</a>

<form id="logout-form-{{ $id }}" action="{{ route($route) }}" method="POST" style="display: none;">
    @csrf
</form>

resources/views/Back/includes/mapScript.blade.php
<script>
    function initMap()
    {
        let map_id = '{{ $map_id }}';

        let map_input = '{{ $map_input }}';

        let lat_val = $('#' + map_id).data('lat');

        let lng_val = $('#' + map_id).data('lng');

        var map = new google.maps.Map(document.getElementById(map_id), { center: {lat: lat_val, lng: lng_val}, zoom: 15 });

        var input = document.getElementById('searchInput');

        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();

        var marker = new google.maps.Marker({
            position: {lat: lat_val, lng: lng_val},
            map: map,
            anchorPoint: new google.maps.Point(0, -29),
            draggable :true
        });

        google.maps.event.addListener(map, 'click', function (event) {
            $('#map_settings_input').val(event.latLng.lat() + ',' + event.latLng.lng());
            //document.getElementById("geo_lat").value = event.latLng.lat();
            //document.getElementById("geo_lng").value = event.latLng.lng();
            marker.setPosition(event.latLng);
        });

        marker.addListener('position_changed', printMarkerLocation);

        function printMarkerLocation() {
            $('#map_settings_input').val(marker.position.lat() + ',' + marker.position.lng());
            //document.getElementById('geo_lat').value = marker.position.lat();
            //document.getElementById('geo_lng').value = marker.position.lng();
        }

        autocomplete.addListener('place_changed', function ()
        {
            infowindow.close();

            marker.setVisible(false);

            var place = autocomplete.getPlace();

            if (!place.geometry)
            {
                window.alert("Autocomplete's returned place contains no geometry");
                return;
            }

            // If the place has a geometry, then present it on a map.
            if (place.geometry.viewport)
            {
                map.fitBounds(place.geometry.viewport);
            }
            else
            {
                map.setCenter(place.geometry.location);
                map.setZoom(17);
            }

            marker.setIcon(({ url: place.icon, size: new google.maps.Size(71, 71), origin: new google.maps.Point(0, 0), anchor: new google.maps.Point(17, 34), scaledSize: new google.maps.Size(35, 35) }));

            marker.setPosition(place.geometry.location);
            marker.setVisible(true);

            $('#' + map_input).val(place.geometry.location.lat()+','+place.geometry.location.lng());

        });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&callback=initMap&key={{ getSetting('map_api') }}" ></script>

resources/views/Back/includes/permissions.blade.php
<div class="row">
    @foreach(getAllRoutes() as $key => $value)
        @if(is_array($value))
            <div class="col-md-6">
                <div class="panel panel-success">
                    <div class="panel-heading">@lang('crud.' . $key)</div>
                    <div class="panel-body">
                        <ul class="list-group">
                            @foreach($value as $k => $val)
                                <li class="list-group-item">
                                    <div class="checkbox checkbox-switchery switchery-lg">
                                        <label>
                                            <input
                                                type="checkbox"
                                                @isset($role) {{ edit_permissions($role->permissions, $val) }} @endisset
                                                class="form-control form-data switchery"
                                                value="{{$val}}"
                                                name="permissions[]"
                                                id="permissions_{{$k}}">
                                            @lang('crud.' . $val)
                                        </label>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @else
            <div class="col-md-6">
                <div class="panel panel-success">
                    <div class="panel-heading">@lang('crud.' . $value)</div>
                    <div class="panel-body">
                        <div class="checkbox checkbox-switchery switchery-lg">
                            <label>
                                <input
                                    type="checkbox"
                                    @isset($role) {{ edit_permissions($role->permissions, $value) }} @endisset
                                    class="form-control form-data switchery"
                                    value="{{$value}}"
                                    name="permissions[]"
                                    id="permissions_{{$key}}">
                                @lang('crud.' . $value)
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    @endforeach
</div>

resources/views/Back/includes/quick-links.blade.php
<ul class="breadcrumb-elements" style="float: {{ floating('left', 'right') }};position: relative;{{ floating('left', 'right') }}: 51px;">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon-gear position-left"></i>@lang('back.quick-links')
            <span class="caret"></span>
        </a>

        <ul class="dropdown-menu dropdown-menu-right">
            <li><a href="{{ route('admins.index') }}"><i class="icon-user-tie"></i> @lang('back.display-all',['var'=>trans('back.admins')])</a></li>

            <li><a href="{{ route('admins.create') }}"><i class="icon-user"></i> @lang('back.create-var',['var'=>trans('back.admin')])</a></li>
        </ul>
    </li>
</ul>

resources/views/Back/includes/sendMail.blade.php
<!-- Basic modal -->
<div id="view_send_mail_model" class="modal fade" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h5 class="modal-title" style="float: right;">@lang('backend.send-mail')</h5>
			</div>

			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						{!! Form::open(['url'=>route('send-mail-post'),'method'=>'POST']) !!}
						<div class="form-group {{ $errors->first('to' , 'has-error') }}">
							<div class="form-valid floating">
								{!! Form::text('to',null,['placeholder'=>trans('backend.to'),'dir' => direction(),'class'=>'form-control wow fadeInUp form-data','id' =>'to']) !!}
								{!! $errors->first('to','<div class="help-block text-right animated fadeInDown val-error">:message</div>') !!}
							</div>
						</div>
						<div class="form-group {{ $errors->first('subject' , 'has-error') }}">
							<div class="form-valid floating">
								{!! Form::text('subject',null,['placeholder'=>trans('backend.subject'),'dir' => direction(),'class'=>'form-control wow fadeInUp form-data','id' =>'subject']) !!}
								{!! $errors->first('subject','<div class="help-block text-right animated fadeInDown val-error">:message</div>') !!}
							</div>
						</div>
						<div class="form-group {{ $errors->first('message' , 'has-error') }}">
							<div class="form-valid floating">
								{!! Form::textarea('message',null,['placeholder'=>trans('backend.message'),'dir' => direction(),'class'=>'form-control wow fadeInUp form-data','id' =>'message']) !!}
								{!! $errors->first('message','<div class="help-block text-right animated fadeInDown val-error">:message</div>') !!}
							</div>
						</div>
						<div class="form-group">
							<input type="submit" name="submit" class="btn btn-primary" style="float: {{ floating('right', 'left') }}" value="@lang('backend.send')">
						</div>
						{!! Form::close() !!}
					</div>
				</div>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">@lang('backend.close')</button>
			</div>
		</div>
	</div>
</div>
<!-- /basic modal -->

resources/views/Back/includes/setEmployeesChart.blade.php
@forelse($usersChart as $res) ['{{ $res->name }}', {{ $res->salary }}],
@empty ['{{ trans('back.no-value') }}', 0]
@endforelse

resources/views/Back/includes/settingsInput.blade.php
@if($setting->input == 'text')
    <div class="form-group">
        <label for="{{$setting->key}}">{{ucwords($setting->name)}}</label>
        <input type="text" class="form-control" name="{{$setting->key}}" id="{{$setting->key}}" value="{{$setting->value}}">
    </div>
@else
    <div class="form-group">
        <label for="{{$setting->key}}">{{ucwords($setting->name)}}</label>
        <textarea class="form-control" name="{{$setting->key}}" id="{{$setting->key}}" cols="30" rows="10">{{$setting->value}}</textarea>
    </div>
@endif