routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect','localizationRedirect','localeViewPath', 'httpsProtocol']
],
function()
{
    # User Login
    Route::group(['namespace' => 'Auth'], function() {
        Route::get('/login', 'LoginController@showUserLoginForm')->name('login');
        Route::post('/login', 'LoginController@userLogin')->name('user.submit.login');
        Route::post('/logout', 'LoginController@userLogout')->name('user.logout');
    });

    # Admin Login
    Route::group(['prefix' => 'admin-panel', 'namespace' => 'Auth\Admin'], function() {
        Route::get('/login', 'AdminLoginController@showAdminLoginForm')->name('admin-panel.login');
        Route::post('/login', 'AdminLoginController@adminLogin')->name('admin.submit.login');
        Route::post('/logout', 'AdminLoginController@adminLogout')->name('admin.logout');
    });

    // Password Reset Routes...
    Route::group(['prefix' => 'password'], function() {
        Route::get('/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.update');
        Route::post('/reset', 'Auth\ResetPasswordController@reset')->name('password.reset');
        Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
        Route::get('/email','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');
    });

    # Admin routes
    Route::group([
        'prefix'     => 'admin-panel',
        'namespace'  => 'Back',
        'middleware' => ['auth:admin', 'CheckAdminRole']
    ],
    function()
    {
        Route::get('/', 'DashboardController@index')->name('admin-panel');

        // admin -> roles Routes
        Route::resource('roles','RoleController', ['except' => ['show']]);
        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function() {
            Route::post('/ajax-delete-role',      'RoleController@DeleteRole')->name('ajax-delete-role');
            Route::post('/ajax-change-role-status', 'RoleController@ChangeStatus')->name('ajax-change-role-status');
            Route::get('/export',                 'RoleController@export')->name('export');
        });

        // admin -> users Routes
        Route::resource('employees', 'EmployeeController', ['except' => ['show']]);
        Route::group(['prefix' => 'employees', 'as' => 'employees.'], function() {
            Route::post('/ajax-delete-employee','EmployeeController@DeleteEmployee')->name('ajax-delete-employee');
            Route::post('/ajax-change-employee-status','EmployeeController@ChangeStatus')->name('ajax-change-employee-status');
            Route::get('/show/{id}','EmployeeController@showEmployee')->name('show-employee');
            Route::get('/export','EmployeeController@export')->name('export');
        });

        // admin -> Settings Routes
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function() {
            Route::post('/ajax-change-setting-status', 'SettingController@ChangeStatus')->name('ajax-change-setting-status');
            Route::get('/export',                    'SettingController@export')->name('export');
            Route::post('/update-all', 'SettingController@UpdateAll')->name('update-all');
            Route::post('/ajax-delete-setting', 'SettingController@DeleteSetting')->name('ajax-delete-setting');
            //Route::get('/show-push-notification', 'AdminController@ShowPushNotification')->name('show-push-notification');
            //Route::post('/show-push-notification-post', 'AdminController@ShowPushNotificationPost')->name('push-notification-post');
        });
        Route::resource('settings', 'SettingController');

        // admin -> Admins Routes
        Route::group(['prefix' => 'admins', 'as' => 'admins.'], function() {
            Route::get('/admin/profile',   'AdminController@adminProfile')->name('profile');
            Route::post('/admin/profile',  'AdminController@AdminUpdateProfile')->name('admin-profile-update');
            Route::post('/ajax-delete-admin',      'AdminController@DeleteAdmin')->name('ajax-delete-admin');
            Route::post('/ajax-change-admin-status', 'AdminController@ChangeStatus')->name('ajax-change-admin-status');
            Route::get('/show/{id}',               'AdminController@showAdmin')->name('show-admin');
            Route::get('/export',                  'AdminController@export')->name('export');
        });
        Route::resource('admins',      'AdminController', ['except' => ['show']]);

        Route::group(['prefix' => 'contacts', 'as' => 'contacts.'], function(){
            Route::get('/',        'AdminController@Contacts')->name('index');
            Route::post('/ajax-delete-contact', 'AdminController@DeleteContact')->name('ajax-delete-contact');
            Route::get('/{id}/message-details', 'AdminController@showMessageDetails')->name('message.details');
            Route::get('/{id}/send-message', 'AdminController@sendUserMessage')->name('send-user-message');
            Route::post('/users-send-email', 'AdminController@SendUserReplayMessage')->name('users-send-email');
            Route::get('/export', 'AdminController@ContactsExport')->name('export');
        });
    });

    # User Routes
    Route::group(['namespace' => 'Front'], function() {
        Route::get('/', 'HomeController@welcome');
        Route::get('/home', 'HomeController@index');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticate;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image as Img;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\File;

class User extends Authenticate
{
    use Notifiable, SoftDeletes;

    public $guard = 'web';

    protected $guarded = ['id', 'password_confirmation'];

    protected $hidden = ['password', 'remember_token'];

    protected $casts = ['status' => 'boolean'];

    public function token()
    {
        return $this->hasOne('App\Model\Token');
    }

    public function setStatusAttribute($value)
    {
        if (is_null($value)) $value = false;

        $this->attributes['status'] = (boolean) $value;
    }

    public function getImageUrlAttribute()
    {
        return ($this->image) ? url('public/uploaded/users/' . $this->image) : url('public/admin/img/avatar10.jpg');
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public static function uploadImage($img)
    {
        $filename = 'user_' . Str::random(12) . '_' . date('Y-m-d') . '.' . strtolower($img->getClientOriginalExtension());

        if (!file_exists(public_path('uploaded/users/')))
            mkdir(public_path('uploaded/users/'), 0777, true);

        $path = public_path('uploaded/users/');

        $img = Img::make($img)->save($path . $filename);

        return $filename;
    }

    public static function createUser($userData)
    {
        if (request()->hasFile('image')) $userData['image'] = User::uploadImage($userData['image']);

        else $userData = Arr::except($userData, ['image']);

        return User::updateOrcreate(Arr::except($userData, ['_token', 'password_confirmation']));
    }

    public static function updateUser($userData, $currentUser)
    {
        if (request()->hasFile('image'))
        {
            File::delete('uploaded/users/'.$currentUser->image);

            $userData['image'] = User::uploadImage($userData['image']);
        }

        else $userData = Arr::except($userData, ['image']);

        return $currentUser->update($userData);
    }
}

app/Http/Controllers/Back/AdminController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Admin;
use App\Models\Contact;
use App\Models\Market;
use App\Models\Role;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\AdminsExport;
use App\Exports\ContactsExport;
use App\Exports\PaymentsExport;
use App\Exports\CommissionExport;
use App\Exports\MarketsCallsExport;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;

class AdminController extends Controller
{
    public function index()
    {
        return view('Back.Admins.index', ['admins' => Admin::where('role_id', '!=', 1)->get()]);
    }

    public function Contacts()
    {
        return view('Back.Admins.contacts',['contacts' => Contact::all()]);
    }

    public function showMessageDetails($id)
    {
        if (!$message = Contact::find($id)) return response()->json(['requestStatus'=>false,'message'=>trans('responseMessages.product-not-exist')]);

        return view('Back.Admins.messageDetailsModal', compact('message'))->render();
    }

    public function sendUserMessage($id)
    {
        if(!$message = Contact::find($id)) return response()->json(['requestStatus' => false,'message' => trans('back.message-not-exists')]);

        return view('Back.Admins.sendUserMessageModal', compact('message'));
    }

    public function SendUserReplayMessage(Request $request)
    {
        return Contact::sendUserReplayMessage($request);
    }

    public function export(Request $request){ return Excel::download(new AdminsExport, 'admins.xlsx'); }

    public function ContactsExport(Request $request) { return Excel::download(new ContactsExport, 'contacts.xlsx'); }

    public function showAdmin($admin_id)
    {
        return view('Back.Admins.show', ['admin' => Admin::findOrFail($admin_id)]);
    }

    public function ChangeStatus(Request $request)
    {
        if (!$updateStatus = Admin::updateStatus($request->all(), Admin::find($request->id)))
            return response()->json(['requestStatus' => false, 'message' => trans('api.server-internal-error')]);

        return response()->json(['requestStatus' => true, 'message' => translated('edit','admin')]);
    }

    public function AdminUpdateProfile(Requests\Back\EditAdminProfileRequest $request)
    {
        if (Admin::updateAdmin($request->except(['_token', 'submit']), Admin::find($request->admin_id)))
        {
            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else{request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if (request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            else{request()->session()->flash('status','danger');request()->session()->flash('message',__('Server Internal Error 500'));}
        }

        return redirect()->route('admins.profile');
    }

    public function adminProfile()
    {
        return view('Back.Admins.profile', ['admin' => Auth::user()]);
    }

    public function create()
    {
        return view('Back.Admins.create',['roles' => Role::getInSelectForm()]);
    }

    public function store(Requests\Back\CreateAdminRequest $request)
    {
        if(Admin::createAdmin($request->all()))
        {
            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else {request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if(request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Internal Server Error 500')]);
            else {request()->session()->flash('status','danger');request()->session()->flash('message',__('Internal Server Error 500'));}

            return back()->withInputs();
        }
        return redirect()->route('admins.index');
    }

    public function edit(Admin $admin)
    {
        return view('Back.Admins.edit', ['admin' => $admin, 'roles' => Role::getInSelectForm()]);
    }

    public function update(Requests\Back\EditAdminRequest $request, $id)
    {
        $currentAdmin = Admin::find($id);

        if (Admin::updateAdmin($request->all(), $currentAdmin)) {

            if (request()->ajax()) return response()->json(['requestStatus' => true, 'message' => translated('add', 'admin')]);
            else{request()->session()->flash('status','success');request()->session()->flash('message',translated('add', 'admin'));}
        }
        else
        {
            if (request()->ajax()) return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            else{request()->session()->flash('status','danger');request()->session()->flash('message',__('Server Internal Error 500'));}
        }

        return redirect()->route('admins.edit', $currentAdmin->id);
    }

    public function DeleteAdmin(Request $request)
    {
        if(!$admin = Admin::findOrFail($request->id)) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, Admin is not exists !!']);

        try
        {
            $admin->delete();
            return response()->json(['deleteStatus' => true, 'message' => 'Admin Deleted Successfully']);
        }
        catch (Exception $e)
        {
            return response()->json(['deleteStatus' => false,'error' => 'Server Internal Error 500']);
        }
    }

    public function DeleteContact(Request $request)
    {
        if(!$contact = Contact::findOrFail($request->id)) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, Message is not exists !!']);

        try
        {
            $contact->delete();

            return response()->json(['deleteStatus' => true, 'message' => translated('delete','message')]);
        }
        catch (Exception $e)
        {
            return response()->json(['deleteStatus' => false,'error' => 'Server Internal Error 500']);
        }
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Employee;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('Back.index', ['usersChart' => Employee::orderBy('salary', 'DESC')->get()]);
    }
}

resources/views/Back/Admins/contacts.blade.php
@extends('Back.layouts.master')

@section('title', trans('back.contacts'))

@section('content')

<!-- Page header -->
<div class="page-header page-header-default">
    <div class="page-header-content">
        <div class="page-title">
            <h4>
                <i onClick="window.history.go(-1);" style="cursor: pointer;" class="icon-arrow-right6 position-left"></i>
                <span class="text-semibold">@lang('back.dashboard')</span> - @lang('back.contacts')
            </h4>
        </div>
    </div>

    <div class="breadcrumb-line">
        <ul class="breadcrumb" style="float: {{ floating('right','left') }};">
            <li><a href="{{ route('admin-panel') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a></li>
            <li class="active">@lang('back.contacts')</li>
        </ul>

        @include('Back.includes.quick-links')
    </div>
</div>
<!-- /page header -->

<!-- Basic datatable -->
<div class="panel panel-flat" dir="{{ direction() }}" style="margin: 20px;">
    @if(Session::has('success'))
        <div class="alert alert-success">{{Session::get('success')}}</div>
    @elseif(Session::has('danger'))
        <div class="alert alert-danger">{{Session::get('danger')}}</div>
    @endif
    <div class="panel-heading">
        <h5 class="panel-title" dir="{{ direction() }}" style="float: {{ floating('right', 'left') }};">
            @lang('back.contacts') ({{ $contacts->count() }})
        </h5>
        <ul class="breadcrumb-elements" dir="{{ direction() }}" style="float: {{ floating('left', 'right') }};">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-gear position-left"></i></a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li>
                        <a href="{{ route('contacts.export') }}"><i class="icon-file-excel"></i> @lang('back.export-csv')</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>

    <table class="table datatable-basic" id="contacts" style="font-size: 16px;">
        <thead>
            <tr>
                <th>#</th>
                <th>@lang('back.form-email')</th>
                <th>@lang('back.form-message')</th>
                <th>@lang('back.since')</th>
                <th>@lang('back.updated_at')</th>
                <th class="text-center">@lang('back.form-actions')</th>
            </tr>
        </thead>
        <tbody>
            @foreach($contacts as $key => $contact)
            <tr id="contact-row-{{ $contact->id }}">
                <td>{{ $key+1 }}</td>

                <td>
                    <a
                        href='{{route('contacts.message.details', ['id' => $contact->id])}}'
                        class='btn btn-md btn-default message-details-btn'
                        type='button'
                        data-toggle='tooltip'>{{ str()->limit($contact->email,30) }}
                    </a>
                </td>

                <td>{{ str()->limit($contact->message, 30) }}</td>

                <td>{{ $contact->diffForHumans }}</td>
                <td>{{ $contact->diffForHumans }}</td>

                <td class="text-center">
                    <ul class="icons-list">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-menu9"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-{{ floating('right', 'left') }}">
                                <li>
                                    <a href="{{route('contacts.send.user.message', ['id' => $contact->id])}}" class="send-user-message-btn">
                                        <i class="icon-bubbles2"></i>@lang('back.replay')
                                    </a>
                                    <a
                                        data-id="{{$contact->id}}" class="delete-action"
                                        href="{{localeUrl('/admin-panel/contacts/'.$contact->id)}}">
                                        <i class="icon-database-remove"></i>@lang('back.delete')
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
<!-- /basic datatable -->
@stop

@section('scripts')
<script>
    $('table#contacts').on('click', 'a.message-details-btn', function()
    {
        var clickedMessageAnchor = $(this);
        var ajaxUrl = clickedMessageAnchor.attr('href');
        $.ajax({
            type: 'GET',
            url: ajaxUrl,
            success: function(response) {
                $('div#site-modals').html(response);
                if (response.requestStatus && response.requestStatus === false) {
                    $('div#site-modals').html('');
                } else {
                    $('#view_message_details').modal('show');
                }
            },
            error: function(x) { crud_handle_server_errors(x); }
        });
        return false;
    });

    $('table#contacts').on('click', 'a.send-user-message-btn', function()
    {
        var clickedSendMessageAnchor = $(this);
        var ajaxUrl = clickedSendMessageAnchor.attr('href');
        $.ajax({
            type: 'GET',
            url: ajaxUrl,
            success: function(response) {
                $('div#site-modals').html(response);
                if (response.requestStatus && response.requestStatus === false) {
                    $('div#site-modals').html('');
                } else {
                    $('#view_send_message').modal('show');
                }
            },
            error: function(x) { crud_handle_server_errors(x); }
        });
        return false;
    });

    $('a.delete-action').on('click', function(e)
    {
        var id = $(this).data('id');
        var tbody = $('table#contacts tbody');
        var count = tbody.data('count');

        e.preventDefault();

        swal({
            title: "هل انت متأكد من حذف  هذه الرسالة",
            text: "سيتم الحذف بالانتقال لسلة المهملات",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete)
            {
                var tbody = $('table#contacts tbody');
                var count = tbody.data('count');

                $.ajax({
                    type: 'POST',
                    url: '{{ route('contacts.ajax-delete-contact') }}',
                    data: {id: id},
                    success: (response) =>
                    {
                        if(response.deleteStatus)
                        {
                            $('#contact-row-'+id).fadeOut(); count = count - 1;tbody.attr('data-count', count);
                            swal(response.message, {icon: "success"});
                        }
                    },
                    error: (x) => swal("Oops","Something went wrong!","error"),
                });
            }
            else
            {
                swal({
                    title: "رسالة",
                    text: "تم إلغاء العملية",
                    icon: "success",
                    button: "حسنا",
                });
            }
        });
    });
</script>
@stop

resources/views/Back/Admins/form.blade.php
<div class="form-group">
	@include('Back.includes.inputs', [
		'errors' => $errors,
		'type'   => 'text',
		'name'   => 'name',
		'style'  => 'form-control form-data',
		'slug'   => trans('back.form-name'),
	])
</div>

<div class="form-group">
	@include('Back.includes.inputs', [
		'errors' => $errors,
		'type'   => 'text',
		'name'   => 'email',
		'style'  => 'form-control form-data',
		'slug'   => trans('back.form-email'),
	])
</div>

<div class="form-group">
    @include('Back.includes.inputs', [
        'errors' => $errors,
        'type'   => 'select',
        'name'   => 'role_id',
        'list'   => count($roles) > 0 ? ['' => trans('back.select-a-value')] + $roles : [0 => trans('back.no-value')],
        'style'  => 'form-control form-data',
        'slug'   => trans('back.t-permission'),
    ])
</div>

@if(request()->is(app()->getLocale().'/admin-panel/admins/create'))
	<div class="form-group">
		@include('Back.includes.inputs', [
			'errors' => $errors,
			'type'   => 'password',
			'name'   => 'password',
			'style'  => 'form-control form-data',
			'slug'   => trans('back.form-password'),
		])
	</div>
	<div class="form-group">
		@include('Back.includes.inputs', [
			'errors' => $errors,
			'type'   => 'password_confirmation',
			'name'   => 'password',
			'style'  => 'form-control form-data',
			'slug'   => trans('back.form-password-confirm'),
		])
	</div>
@endif

<div class="form-group">
	@include('Back.includes.inputs', [
		'errors' => $errors,
		'type'   => 'image',
		'name'   => 'image',
		'style'  => 'form-control form-data',
		'col'    => '6',
		'slug'   => trans('back.form-image'),
	])
	<div class="col-xs-6">
		<div class="img-container">
			<img id="viewImage" class="img-responsive" width="90" height="90" src="{{ isset($admin) ? $admin->image_url : '' }}"/>
		</div>
	</div>
</div>

<div class="form-group">
	<div class="checkbox checkbox-switchery switchery-lg">
		<label>
			@if(isset($admin)) @php $status = $admin->status == 1 ? true : false; @endphp

			@else @php $status = true; @endphp @endif

			{!! Form::checkbox('status',1, $status,['class'=>'form-control switchery form-data','id' => 'status']) !!}

			@lang('back.form-status')
		</label>
	</div>
</div>

@section('scripts')
<script>
	$('input[name=image]').change(function(){
		readURL(this);
	});
</script>
@stop

resources/views/Back/Admins/index.blade.php
@extends('Back.layouts.master')

@section('title', trans('back.admins'))

@section('content')

<!-- Page header -->
<div class="page-header page-header-default">
    <div class="page-header-content">
        <div class="page-title">
            <h4>
                <i onClick="window.history.go(-1);" style="cursor: pointer;" class="icon-arrow-right6 position-left"></i>
                <span class="text-semibold">@lang('back.dashboard')</span> - @lang('back.admins')
            </h4>
        </div>
    </div>

    <div class="breadcrumb-line">
        <ul class="breadcrumb" style="float: {{ floating('right','left') }};">
            <li><a href="{{ route('admin-panel') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a></li>
            <li class="active">@lang('back.admins')</li>
        </ul>

        @include('Back.includes.quick-links')
    </div>
</div>
<!-- /page header -->

<!-- Basic datatable -->
<div class="panel panel-flat" dir="{{ direction() }}" style="margin: 20px;">
    <div class="panel-heading">
        @include('Back.includes.table-header', ['collection' => $admins, 'name' => 'admins', 'icon' => 'user-tie'])
    </div>

    <table class="table datatable-basic" id="admins" style="font-size: 16px;">
        <thead>
            <tr>
                <th>#</th>
                <th>@lang('back.form-name')</th>
                <th>@lang('back.form-email')</th>
                <th>@lang('back.form-image')</th>
                @if(permission_route_checker('admins.ajax-change-admin-statue'))
                    <th>@lang('back.form-status')</th>
                @endif
                <th>@lang('back.since')</th>
                <th class="text-center">@lang('back.form-actions')</th>
            </tr>
        </thead>
        <tbody>
            @foreach($admins as $key => $admin)
            @if(auth()->user()->id != $admin->id)
            <tr id="admin-row-{{ $admin->id }}">
                <td>{{ $key+1 }}</td>

                <td><a href="{{ route('admins.show-admin', $admin->id) }}">{{ $admin->name ?? trans('back.no-value') }}</a></td>

                <td><a href="mailto:{{ $admin->email }}">{{ str_limit_30($admin->email ?? trans('back.no-value')) }}</a></td>

                <td><img width="60" height="60" class="img-circle" src="{{ $admin->image_url }}" alt=""></td>

                <td>{{ $admin->created_at->diffForHumans() }}</td>

                @if(permission_route_checker('admins.ajax-change-admin-statue'))
                    @include('Back.includes.chnageModelStatus', ['model' => $admin])
                @endif

                <td class="text-center">
                    @include('Back.includes.edit-delete', ['route' => 'admins', 'model' => $admin])
                </td>
            </tr>
            @endif
            @endforeach
        </tbody>
    </table>
</div>
<!-- /basic datatable -->
@stop

@section('scripts')
<script>

    function isChecked(value, id){
        if(value === 'checked'){
            $('#active-id-'+id).attr('onclick', 'isChecked("null", "'+id+'")');
        }else{
            $('#active-id-'+id).attr('onclick', 'isChecked("checked", "'+id+'")');
        }
        $.ajax({
            type: 'POST',
            url: '{{ route('admins.ajax-change-admin-status') }}',
            data: { id: id, value: value },
            success: function(response) {
                new PNotify({
                    title: 'Success notice',
                    text: response.message,
                    addclass: 'bg-success stack-top-right',
                    stack: {"dir1": "down", "dir2": "right", "push": "top"}
                });
            },
            error: (e) => console.error(e),
        });
    }

    $('a.show-admin-halls-btn').on('click', function()
    {
        var clickedSalonAnchor = $(this);
        var ajaxUrl = clickedSalonAnchor.attr('href');
        $.ajax({
            type: 'GET',
            url: ajaxUrl,
            success: function(response) {
                $('div#site-modals').html(response);
                if (response.requestStatus && response.requestStatus === false) {
                    $('div#site-modals').html('');
                } else {
                    $('#view_admin_halls_details').modal('show');
                }
            },
            error: function(x) { crud_handle_server_errors(x); }
        });
        return false;
    });

    $('a.delete-action').on('click', function(e)
    {
        var id = $(this).data('id');
        var tbody = $('table#admins tbody');
        var count = tbody.data('count');

        e.preventDefault();

        swal({
            title: "هل انت متأكد من حذف هذاالمشرف",
            text: "سيتم الحذف نهائيا",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                var tbody = $('table#admins tbody');
                var count = tbody.data('count');

                $.ajax({
                    type: 'POST',
                    url: '{{ route('admins.ajax-delete-admin') }}',
                    data: {id: id},
                    success: function(response)
                    {
                        if(response.deleteStatus)
                        {
                            $('#admin-row-'+id).fadeOut(); count = count - 1;tbody.attr('data-count', count);
                            swal(response.message, {icon: "success"});
                        }
                        else
                        {
                            swal(response.error);
                        }
                    },
                    error: function(x) { crud_handle_server_errors(x); },
                    complete: function() {
                        if(count === 1) tbody.append(`<tr><td colspan="5"><strong>No data available in table</strong></td></tr>`);
                    }
                });
            }
            else
            {
                swal({
                    title: "رسالة",
                    text: "تم إلغاء العملية",
                    icon: "success",
                    button: "حسنا",
                });
            }
        });
    });
</script>
@stop